name: Canyon Brewing Project
favicon: null
layout_spectrum: 0.50179
typography_spectrum: 0.09079652698710561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69952529-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4e3b4'
    - '#3cc39c'
    - '#572931'
    - '#cbb493'
    - '#7d5453'
  brandStrength: 0.05146481888368726
  lightness: 0.6617462579160929
  saturation: 0.7107046514283866
  rhythmicContrast: 0.1842804818879813
purpose: []
